# Compile all netpbm works
netpbm-works:
# cd dissolve && python dissolve.py
# cd mod && python mod.py
# cd drunk_walk && python drunk_walk.py
# cd partition && python partition.py
	cd clip && python clip.py
	cd channel && python channel.py
	cd resolution && python resolution.py
	cd conway && python conway.py
# TODO: uncomment this after testing